# This is a basic workflow to help you get started with Actions

name: Doxygen

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Doxygen Action
        # You may pin to the exact commit or the version.
        # uses: mattnotmitt/doxygen-action@9039b4cfaf5097b76489c53c0cdc8cba59091b57
        uses: mattnotmitt/doxygen-action@1.9.1
        with:
          # Path to Doxyfile
          doxyfile-path: ./Doxyfile
          # Working directory
          working-directory: .
          # Generate latex documentation
          enable-latex: True
          # Extra alpine packages for the build environment
          # additional-packages:
       
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Default Doxyfile build documentation to html directory. 
          # Change the directory if changes in Doxyfile
          publish_dir: ./html
